### ISSUE TITLE
KeyError: 'calResults'

### ISSUE THREAD

**Issue by dscheste** [wenboyu2/yahoo-earnings-calendar#2]
Hello,

I am getting this error when pulling earnings:

> Traceback (most recent call last):
>   File "yahooearnings.py", line 17, in <module>
>     flist = yec.earnings_between(date_from, date_to)
>   File "/home/dscheste/.local/lib/python2.7/site-packages/yahoo_earnings_calendar/scraper.py", line 117, in earnings_between
>     earnings_data += self.earnings_on(current_date)
>   File "/home/dscheste/.local/lib/python2.7/site-packages/yahoo_earnings_calendar/scraper.py", line 80, in earnings_on
>     return page_data_dict['context']['dispatcher']['stores']['CalendarStore']['calResults']['data']['rows']
> KeyError: 'calResults'
> 

And here is my code:

```
import os
import datetime
from datetime import datetime
from datetime import timedelta
import pymysql
import time
from yahoo_earnings_calendar import YahooEarningsCalendar
import pandas as pd
now = (time.strftime("%m-%d-%Y"))
date_from = datetime.now()
print(date_from)
date_to = date_from + timedelta(days=15)
print(date_to)
yec = YahooEarningsCalendar()
flist = yec.earnings_between(date_from, date_to)
print(flist)

```

Any suggestions on how I can fix it?

**Comment by dscheste** [comment]
I dug a little bit and I think yahoo has changed their component naming.

Changing line 80 to
        return page_data_dict['context']['dispatcher']['stores']['ScreenerResultsStore']['results']['rows']
fixed the issue.

**Comment by tgtwm1github** [comment]
Hello,

Can you please tell me how to install the codeset with your change? I downloaded and edited the code but unable to install it.

I have already run pip install yahoo-earnings. So if I need to uninstall, before I can install the codeset please I need that command as well.

Thanks so much.
