### ISSUE TITLE
single quote YEC seems not providing correct answer

### ISSUE THREAD

**Issue by tgtwm1github** [wenboyu2/yahoo-earnings-calendar#4]
I tried to get the next earnings data for FB or ORCL for example
here is what I got

Oracle earnings came today so I expected today's date or a future date.
I'm not sure what the below date means. Please help.
>>> import datetime
>>> from yahoo_earnings_calendar import YahooEarningsCalendar
>>> yec = YahooEarningsCalendar()
>>> print yec.get_next_earnings_date('fb')
1509408000
>>> print yec.get_next_earnings_date('orcl')
1505260800
>>>

**Comment by wenboyu2** [comment]
`1509408000` is Unix timestamp, you can convert that to a readable date with python `datetime` or websites like this https://www.epochconverter.com/

**Comment by tgtwm1github** [comment]
Thanks.
